[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_loadset('filename','RVS_Subject115_Training1_256__Luck_stim.set','filepath','Y:\\Prosjekt\\RVS_43_subjects\\Analyzed_datasets\\RVS_Subject115\\Training1\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG=pop_chanedit(EEG, 'lookup','Y:\\Prosjekt\\RVS_43_subjects\\Matlab_programs\\eeglab_sml_v3\\eeglab_sml_v3\\plugins\\dipfit2.3\\standard_BESA\\standard-10-5-cap385.elp');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_saveset( EEG, 'savemode','resave');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
figure; pop_timtopo(EEG, [-199.2188       796.875], [NaN], 'ERP data and scalp maps of RVS_Subject115_Training1_256__Luck_stim');
EEG = eeg_checkset( EEG );
figure; pop_timtopo(EEG, [-199.2188       796.875], [91  108  162  273  390  548], 'ERP data and scalp maps of RVS_Subject114_Training1_256__Luck_stim');
EEG = pop_loadset('filename','RVS_Subject114_Training2_256__Luck_stim.set','filepath','Y:\\Prosjekt\\RVS_43_subjects\\Analyzed_datasets\\RVS_Subject114\\Training2\\');
[ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
EEG=pop_chanedit(EEG, 'lookup','Y:\\Prosjekt\\RVS_43_subjects\\Matlab_programs\\eeglab_sml_v3\\eeglab_sml_v3\\plugins\\dipfit2.3\\standard_BESA\\standard-10-5-cap385.elp');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
EEG = pop_saveset( EEG, 'savemode','resave');
[ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
EEG = eeg_checkset( EEG );
figure; pop_timtopo(EEG, [-199.2188       796.875], [NaN], 'ERP data and scalp maps of RVS_Subject114_Training2_256__Luck_stim');